### ISSUE TITLE
Handler function does not contain run?

### ISSUE THREAD

**Issue by pixelcommerce** [skpm/skpm#110]
As I was writing my plugin, this weird error came up that stops my plugin from functioning properly: 
`Error in command conStrest Script at path /Users/laptopname/Desktop/Sketch Plugins/plugin-directory/plugin.sketchplugin/Contents/Sketch/my-command.js does not contain a handler function named: run.` What does this mean?

I gave a handler/action list to a function like so: 

```json
{
  "compatibleVersion": 3,
  "bundleVersion": 1,
  "commands": [
    {
      "name": "array",
      "identifier": "list-array-doohig",
      "script": "./my-command.js",
      "handlers" : {
          "actions" : {
              "OpenDocument.finish" : "conStrest"
          }
      }
    }
  ]
}
```

I thought if I gave a handler a function name, the name "run" wasn't necessary anymore?

The JS file is as such: 

`export function conStrest(context) {
  context.document.showMessage("It's alive 🙌")
}
`

I just tweaked the function name to see if things would work... it didn't...

**Comment by mathieudutour** [comment]
I think it's because you are using `npm run start` which runs the command on every change. Use `npm run watch` instead.

**Comment by pixelcommerce** [comment]
AH. That's interesting... Thanks for the heads up!

**Comment by madordie** [comment]
I also encountered the same problem.

My `.js` does not specify `default` or `onRun`, but `skpm` still generates `that['onRun'] = __skpm_run.bind(this, 'default');`. so . missing part of the code in the js file is: `that['SEL'] = __skpm_run.bind(this, 'SEL');` and the final error is as follows: `Error in command toggles the selected item Script at path /Users/Madordie /Desktop/Madordie/3rdPart/sketch-sync/sync-npm/plugin.sketchplugin/Contents/Sketch/my-command.js does not contain a handler function named: projectSel.`

My solution to this problem is to add a `default` identifier to one of the methods in the `.js` file. About this way:

```js
export default function projectSel(context) {
...
}
```

I'm not proficient with js, so I can't deduce the real reason...🤷‍♂️
