### ISSUE TITLE
Failed to get correct selectedDocument

### ISSUE THREAD

**Issue by nichenqin** [skpm/skpm#121]
## What I have done

I open a new sketch document which named untitled by default and open my plugin(created by sketch-module-web-view), I can do something inside the sketch.
Then I create a new sketch document(command + N) which named untitled 243(may be), and when I do something in the plugin the effect always show in the first document window.

## What I expect

I hope everything I do in plugin will show in the current document window which I have focused latest.

## Others

I find that the `sketch-dev-tool` plugin created by you knows which document is selected and can log each document objectID in playground tab(`console.log(context.api().selectedDocument.selectedPage.id)`). And when I swipe down with four fingers to show App Exposé, I can see the dev tool panel. Is there any config I might have missed to toggle between document window? (I have browse the code of `sketch-dev-tool` but failed to figure it out).

Thanks for your help!

**Comment by mathieudutour** [comment]
I don't think that is related to skpm?

I think you are talking about `context.document` (or `context.api().selectedDocument` which is the same)? The context doesn't change when the user changes the document while your plugin is running, it will still be the document selected when the script was started.
It usually doesn't matter but since you are using a webview, the script never stops and so the context never change. you can use `NSDocumentController.sharedDocumentController().currentDocument()` to get the actual selected document.

> And when I swipe down with four fingers to show App Exposé, I can see the dev tool panel. Is there any config I might have missed to toggle between document window?

I don't understand sorry
