### ISSUE TITLE
How about SKPM plugins list?

### ISSUE THREAD

**Issue by zmnv** [skpm/skpm#125]
skpm is a w e s o m e.

I would like to find other plugins with skpm, but google is so stupid in that part....
Also, for developers it will be great place to find eachothers )

**Comment by mathieudutour** [comment]
Thanks!

Do you mean https://www.sketchapp.com/extensions/plugins/ ?

**Comment by zmnv** [comment]
1. **Yeah, like that** or like a [list on github](https://github.com/sketchplugins/plugin-directory), but only JS-plugins with skpm (maybe with react/any framework).

Can I ask some questions here? I don't like chats, pls.
I see you are in list **Bohemian** team, so..

2. Is the **skpm** an **official** tool for Sketch with endless support? 

Nowtime I feel changes in Force... Master Katarn... That feels looks like a TREND to transition all plugin system from **Objective-C** to holy **Javascript**.  Am I right?  So.. if that true — why didn't you create SKPM before Sketch?  

3. Really? Only 4 people creates **Sketchapp**? Really??

4. Do you have an communications and teamwork with **airbnb**? **react-sketchapp** is awesome, but contains more **React Native** things than just **React**... Also its sooo big for my purpose.

I just wanna change colors and text/positions in already drawn sketch-file, not to create new page by js code like **react-sketchapp**. One time I found **[CSSketch](https://github.com/JohnCoates/CSSketch)**, whit was perfect for me! Colors changes In REALTIME! But.... it just was........

New versions of Sketch just broke that plugin, and author don't doing on that. 
No more updates... But I need it.

Can you tell me. Is that easy to just create plugin which — **Realtime Updates Sketch-file layers style with CSS / SASS / LESS / SCSS**? I just scan **CSSketch** source code in **Objective C** and ... this is unacceptable to me. I think my desire can be realized more faster with **skpm**. Or not?

**Comment by mathieudutour** [comment]
1. I'm hoping that Github will soon be able to list the repo that depends on `@skpm/builder` here: https://github.com/skpm/skpm/network/dependents so it will be easier to check who uses it (it doesn't work with scoped packages for now).

2. Yes skpm is now the go-to tool to create plugin and I'll maintain it. We do want to push people to use JS instead of Obj-C since it's a lot safer and can be inspected in a more easier way.

> why didn't you create SKPM before Sketch?

I did create skpm before joining sketch. Not sure what you are asking.

3. No we are about 25

4. Yes I'm talking with some people at airbnb and I'm also contributing a bit to react-sketchapp but only in my spare time, it is not my "official" job.

it's not "easy" to create such a plugin but it is def possible
