### ISSUE TITLE
skpm publish appcast is reading local and remote

### ISSUE THREAD

**Issue by tbrasington** [skpm/skpm#213]
Hello

I am running `skpm publish minor` and I am getting this error

```
t.brasington$ skpm publish minor 
⠋ Bumping package.json version and creating git tag
✖ ERROR Error: ENOENT: no such file or directory, open '/Users/t.brasington/Sites/sketch/text-to-styles/https:/raw.githubusercontent.com/tbrasington/text-to-styles/master/.appcast.xml'
Error: ENOENT: no such file or directory, open '/Users/t.brasington/Sites/sketch/text-to-styles/https:/raw.githubusercontent.com/tbrasington/text-to-styles/master/.appcast.xml'

```

Not sure what has happened since my last publish that is causing it to look in my local and remote source of the appcast file. 

Do i need to change my manifest or package setup to something different? My repo is here https://github.com/tbrasington/text-to-styles

Thank you in advance!

**Comment by mathieudutour** [comment]
So you don't have to specify the appcast here: https://github.com/tbrasington/text-to-styles/blob/master/package.json#L18 because that's the default.

The field is used to specify the path to the appcast in case you want to host it somewhere else (to update the manifest.json). There used to be a bug that didn't take it into account and now it's fixed.

**Comment by tbrasington** [comment]
As always, thank you for the help @mathieudutour
