### ISSUE TITLE
Change Publish message

### ISSUE THREAD

**Issue by prateekrastogi** [skpm/skpm#269]
Hi,

I tried using skpm to publish on CI/CD setup. After managing to publish, I got greeted with commit msg containing eye-soaring emojis such as `Publish 0.0.53 release 🚀 `. 

Are there any options to customize commit msg templates, or any workarounds?

Even skpm repo doesn't use emojis in its commit.

**Comment by mathieudutour** [comment]
There isn't. Happy to accept a PR to add `-m` option to the publish command.

(Please refrain from passive aggressive issue: "eye-soaring"... I did write that commit message and use emojis often in commit messages because they are easily parsable visually. You are welcome to have your own opinion without shutting others down.)
